#!/usr/bin/python
import urllib2
import sys
#Attempt to connect to my site to see current version
try:
	link = "http://getsometunes.net/CURR_VERSION_NUMBER.html"
	page = urllib2.urlopen(link)
	data = page.read()
except:
#just exit if it can't connect
	exit(0)
currLine = "" 
inTag = True
#Currently its 1.0.0
versionNum = 110 

otherVersionNum = 0
#The format of the html file is <NUM>
#which is why the below works
for line in data:
	if(line == ">"):
		#inTag makes it so we only grab the first line
		inTag = False
	elif(line == "<"):
		pass
	elif(inTag == True):       
		currLine += line
try:
#Try here to deal with if it doesnt get a number, better safe than sorry
	otherVersionNum = int(currLine)
	if(otherVersionNum > versionNum):
		print("UPDATE IS AVAILABLE")
		print("Please visit http://getsometunes.net")
		print("To download the latest version")
except:
	pass
